### ISSUE TITLE
Исправь пожалуйста так как в задании название таблицы 

### ISSUE THREAD

**Issue by Muxamedin** [CarbonSkorobogatov/Python#1]
Исправь пожалуйста так как в задании название таблицы 
https://github.com/CarbonSkorobogatov/Python/blob/375692f98537ed2d5b637922380975bc75e6acf8/hm-2/task6.py#L3

**Comment by CarbonSkorobogatov** [comment]
Исправил

ср, 21 июл. 2021 г. в 12:25, Mikel Bily ***@***.***>:
