### ISSUE TITLE
Код рабочий - не соблюдены стили написания кода 

### ISSUE THREAD

**Issue by Muxamedin** [CarbonSkorobogatov/Python#2]
https://github.com/CarbonSkorobogatov/Python/blob/c172038ed496d75ebf587f363ae70a0e90ab6e78/hm-3/task1.py#L8
Вместо :
if client_password == PASSWORD: print("В вошли в учётную запись")
else: print("Не верный пароль")

Предпочтительно
if client_password == PASSWORD:
	print("В вошли в учётную запись")
else: 
	print("Не верный пароль")
	
Либо можно использовать тернарную конструкцию

print("В вошли в учётную запись" if client_password == PASSWORD else "Не верный пароль" )

**Comment by CarbonSkorobogatov** [comment]
Спасибо за замечание, исправил

ср, 28 июл. 2021 г. в 11:03, Mikel Bily ***@***.***>:
