### ISSUE TITLE
Написание конструкции работать будет, но код от этого не  становится удобным для чтения

### ISSUE THREAD

**Issue by Muxamedin** [CarbonSkorobogatov/Python#3]
https://github.com/CarbonSkorobogatov/Python/blob/c172038ed496d75ebf587f363ae70a0e90ab6e78/hm-3/task2.py#L18
Давайте с самого начала приучим себя к однотипности написания кода 
if a == b: print(f'a = {a}, b = {b}')

прекрасно бы смотрелся вот так 
if a == b: 
    print(f'a = {a}, b = {b}')
    
 Рекомендую исправить

**Comment by CarbonSkorobogatov** [comment]
Исправил


ср, 28 июл. 2021 г. в 11:08, Mikel Bily ***@***.***>:
