### ISSUE TITLE
При вводе чисел не из диапазона - приложение не предупреждает об этом 

### ISSUE THREAD

**Issue by Muxamedin** [CarbonSkorobogatov/Python#4]
https://github.com/CarbonSkorobogatov/Python/blob/761f27c512048179649c37e28140c71a697e3df7/hm-5/game.py#L23

См.задание >> "При вводе неправльного числа или не числа - выдвать сообщение об ошибке игрока и считать как попытка."
![image](https://user-images.githubusercontent.com/4419752/128254796-dca2480f-70fa-4738-ba59-a29fb44bc126.png)

 В данном случае 0 и -3 не в диапазоне - но нету предупреждения об ошибке

**Comment by CarbonSkorobogatov** [comment]
Исправил и обновил

чт, 5 авг. 2021 г. в 00:08, Mikel Bily ***@***.***>:
