### ISSUE TITLE
Пожалуйста не записывайте больше переменне большими символами

### ISSUE THREAD

**Issue by Muxamedin** [CarbonSkorobogatov/Python#5]
https://github.com/CarbonSkorobogatov/Python/blob/761f27c512048179649c37e28140c71a697e3df7/hm-5/pyramide.py#L14
Пожалуйста не записывайте больше переменне большими символами , так как такую запись принято  считать переменной хранящюю константное значение и оно не меняется

**Comment by CarbonSkorobogatov** [comment]
Исправил и обновил



чт, 5 авг. 2021 г. в 00:16, Mikel Bily ***@***.***>:
