### ISSUE TITLE
Рекомендация 

### ISSUE THREAD

**Issue by Muxamedin** [CarbonSkorobogatov/Python#6]
Хорошая работа !

Стиль написания кода (PEP8):
В коментариях нужно отступать от сивола решетки один пробел :)
 
https://github.com/CarbonSkorobogatov/Python/blob/ae3adb2a8ce45c0652f38a87f1a75b9f5862f40d/hm-6/find_element.py#L9

**Comment by CarbonSkorobogatov** [comment]
Спасибо, уже пофиксил комментарии и буду знать как правильно их оформлять)

>
