### ISSUE TITLE
ERROR!!!!!

### ISSUE THREAD

**Issue by Muxamedin** [CarbonSkorobogatov/Python#7]
https://github.com/CarbonSkorobogatov/Python/blob/9b19e9a1c52686569e5133a2c9dbca674981f3da/hm-6/add_element_in_list.py#L3

**Comment by CarbonSkorobogatov** [comment]
Да я ошибся с range


сб, 7 авг. 2021 г. в 12:13, Mikel Bily ***@***.***>:
