### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Muxamedin** [CarbonSkorobogatov/Python#8]
https://github.com/CarbonSkorobogatov/Python/blob/9b19e9a1c52686569e5133a2c9dbca674981f3da/hm-6/remove_element_in_list.py#L3

**Comment by CarbonSkorobogatov** [comment]
Исправил

сб, 7 авг. 2021 г. в 12:15, Mikel Bily ***@***.***>:

**Comment by CarbonSkorobogatov** [comment]
Я там перепутал метод(((


сб, 7 авг. 2021 г. в 12:18, lyatoslav skorobohatov ***@***.***>:

**Comment by Muxamedin** [comment]
там нету метода !!! :) 
там функция !
