### ISSUE TITLE
Так сколько раз в строке встречается каждое слово ? 

### ISSUE THREAD

**Issue by Muxamedin** [CarbonSkorobogatov/Python#9]
В единственной строке записан текст. Для каждого слова из данного текста подсчитайте, сколько раз оно встречалось в этом тексте.

![image](https://user-images.githubusercontent.com/4419752/129270918-cac30b52-fc60-47b8-af06-a2821b950a30.png)

https://github.com/CarbonSkorobogatov/Python/blob/fa41af39353ac22a5fb942385e13abbdb7721ff2/hm-7/dict_count_word_in_line.py#L27

**Comment by CarbonSkorobogatov** [comment]
Все исправил, теперь возвращает словарь, где ключ - єто количество
повторений, а значение список слов

пт, 13 авг. 2021 г. в 00:15, Mikel Bily ***@***.***>:
